- name: Install HAProxy
  ansible.builtin.package:
    name: 'haproxy'
    state: present

- name: Get HAProxy version.
  command: haproxy -v
  register: haproxy_version_result
  changed_when: false
  check_mode: false
  ignore_errors: "{{ ansible_check_mode }}"

- name: Copy HAProxy Configuration
  template:
    src: haproxy.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644

- name: Start and Enable HAProxy
  ansible.builtin.service:
    name: haproxy
    state: restarted
    enabled: yes
  check_mode: false
  ignore_errors: "{{ ansible_check_mode }}"
    
