---

- name: Ensure Systems are Updated
  hosts: all
  become: true
  gather_facts: false
  roles:
    - update
  tags: 
    - "update"
    - "all"

# this should be using variables and etc
- name: Configure Firewall Ports
  hosts: haproxy
  become: true
  gather_facts: false
  roles:
    - firewall
  tags:
    - "firewall"
    - "haproxy"

- name: Ensure HAProxy is Installed and Configured
  hosts: haproxy
  become: true
  roles:
    - haproxy
  tags: 
    - "haproxy"

- name: Create and Configure Gateway User
  hosts: all
  become: true
  gather_facts: false
  roles:
    - users
  tags: 
    - "user"
    - "haproxy"

- name: Ensure Fluentd Container Is installed
  hosts: haproxy
  become: true
  gather_facts: false
  roles:
    - fluentd
  tags:
    - "fluentd"
    - "haproxy"

- name: Create and Run Nginx Container
  hosts: gateway
  become: true
  become_user: gateway
  gather_facts: false
  roles:
    - nginx
  tags: 
    - "nginx"
    - "flex"

- name: Create and Run Gateway Container
  hosts: none
  become: true
  gather_facts: false
  roles:
    - "flex"
  tags: 
    - "flex"
  check_mode: true
