---

- name: Ensure Podman is Installed
  ansible.builtin.package:
    name: 'podman'
    state: latest

- name: Make log folder
  ansible.builtin.file:
    path: /data
    owner: gateway
    mode: '0644'
    state: directory

# do i need to pull the image? 
# or just pull and run at the same time

- name: Pull Fluentd Image
  become_user: gateway
  containers.podman.podman_image:
    name: docker.io/fluent/fluentd:v1.15.3-1.0
  tags: "pulling image"
  check_mode: false
  ignore_errors: "{{ ansible_check_mode }}"

- name: Create and Enable Fluentd Container
  become_user: gateway
  containers.podman.podman_container:
    name: fluentd
    image: docker.io/fluent/fluentd:v1.15.3-1.0
    state: started
    detach: true
    volume:
      - /data:/fluentd/log
  tags: "running fluentd container"
  check_mode: false
  ignore_errors: "{{ ansible_check_mode }}"



