---

- name: Ensure Podman is Installed
  ansible.builtin.package:
    name: 'podman'
    state: latest
  tags: "flex"

- name: Ensure Gateway Container is Started
  become_user: gateway
  containers.podman.podman_container:
    name: flexgateway
    image: docker.io/library/flex-gateway:1.1.0
    state: started
    detach: true
  tags: "flex"
